# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(choices=[('provider', 'Provider'), ('commissioner', 'Commissioner'), ('alb', "Arm's Length Body (ALB)"), ('independent-provider', 'Independent Provider'), ('local-authority', 'Local Authority'), ('pathology-jv', 'Pathology Joint Venture'), ('other', 'Other')], db_index=True, default='other', max_length=25, verbose_name='organisation type')),
                ('region', models.CharField(blank=True, choices=[('', 'None'), ('Y54', 'North of England'), ('Y55', 'Midlands and East of England'), ('Y56', 'London'), ('Y57', 'South East'), ('Y58', 'South West')], db_index=True, max_length=3)),
                ('closure_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ('name',),
            },
        ),
    ]
