# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhsorganisations', '0004_add_initial_region_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='region_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='nhsorganisations.Region', verbose_name='region'),
        ),
    ]
