# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-08 10:02
from django.db import migrations


def migrate_forwards(apps, schema_editor):
    Organisation = apps.get_model("nhsorganisations", "Organisation")
    Region = apps.get_model("nhsorganisations", "Region")
    regions_by_code = {obj.code: obj for obj in Region.objects.all()}
    for region_code, region in regions_by_code.items():
        Organisation.objects.filter(region=region_code).update(region_new=region)


def migrate_backwards(apps, schema_editor):
    Organisation = apps.get_model("nhsorganisations", "Organisation")
    Organisation.objects.update(region_new=None)


class Migration(migrations.Migration):
    dependencies = [
        ('nhsorganisations', '0005_add_new_region_field_to_organisation'),
    ]

    operations = [
        migrations.RunPython(migrate_forwards, migrate_backwards),
    ]
