# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-06 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhsorganisations', '0007_auto_20190205_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='region',
        ),
    ]
