# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-06 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhsorganisations', '0008_remove_organisation_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='region_new',
            new_name='region',
        ),
    ]
