# Generated by Django 2.2.3 on 2019-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhsorganisations', '0011_add_additional_region_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_type',
            field=models.CharField(choices=[('provider', 'Provider'), ('commissioner', 'Commissioner'), ('alb', "Arm's Length Body (ALB)"), ('independent-provider', 'Independent Provider'), ('local-authority', 'Local Authority'), ('pathology-jv', 'Pathology Joint Venture'), ('gp-practice', 'GP Practice'), ('dentist', 'Dentist'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], db_index=True, default='other', max_length=25, verbose_name='organisation type'),
        ),
    ]
